stages:
  prepare_dataset:
    cmd: python mrec/data/make_dataset.py
    deps:
    - dataset/raw/test.csv
    - dataset/raw/train.csv
    - dataset/raw/validation.csv
    - mrec/data/make_dataset.py
    outs:
    - dataset/processed
  train:
    cmd: python mrec/train_mrec.py
    deps:
    - dataset/processed
    - mrec/train_mrec.py
    params:
    - train.degree
    - train.kernel
    - train.nu
    - train.random_state
    outs:
    - models/clean_data_model
